apiVersion: v1
kind: Secret
metadata:
  name: s3-creds
  namespace: kube-system
type: Opaque
stringData:
  key_id: "accessKey1"      # Replace with your access key
  access_key: "verySecretKey1"  # Replace with your secret key
  endpoint: "http://192.168.1.70:8000"